apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-svc
  labels:
    app: fraud-detection
spec:
  type: LoadBalancer
  selector:
    app: fraud-detection
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
